spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lvmopdracht3
    username: VanMoerUser
    password: VanMoerPass.2018
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
server:
  port: 8081